# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/PuloV/ics-golang
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v -cover -coverprofile=/tmp/test-results/coverage.out ./... > /tmp/test-results/results.json

      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results
